# Generated by Django 3.2.5 on 2021-11-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('newid', models.IntegerField(null=True, unique=True)),
                ('dprsubdate', models.DateField(null=True)),
                ('amt_asked', models.FloatField()),
                ('amt_approved', models.FloatField(null=True)),
                ('amt_released', models.FloatField(null=True)),
                ('schedule', models.IntegerField(null=True)),
                ('fundcategory', models.CharField(max_length=20, null=True)),
                ('projectpath', models.TextField(null=True)),
                ('quantumOfFunding', models.FloatField(null=True)),
                ('status', models.CharField(default='1', max_length=1, null=True)),
                ('submitted_boq', models.TextField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('deny', models.BooleanField(default=False)),
                ('remark', models.TextField(null=True)),
                ('denydate', models.DateField(null=True)),
                ('approvedate', models.DateField(null=True)),
                ('tesg_list', models.TextField(null=True)),
                ('dpraprdate', models.DateField(auto_now_add=True, null=True)),
                ('tesgaprdate', models.DateField(null=True)),
                ('appraprdate', models.DateField(null=True)),
                ('moniaprdate', models.DateField(null=True)),
                ('workflow', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TESG_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TESG_no', models.IntegerField(unique=True)),
                ('filepath', models.TextField(null=True)),
                ('TESG_date', models.DateField(null=True)),
                ('projects', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('nodal', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('email', models.TextField(max_length=50, null=True)),
                ('utilname', models.CharField(max_length=400, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('reqdate', models.DateField(auto_now_add=True, null=True)),
                ('aprdate', models.DateField(null=True)),
                ('lastlogin', models.DateTimeField(null=True)),
                ('admin', models.BooleanField(default=False)),
                ('auditor', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('activate', models.BooleanField(default=False)),
                ('notification', models.TextField(null=True)),
                ('tpd', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TESG_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_response', models.TextField(null=True)),
                ('user_filepath', models.TextField(null=True)),
                ('user_res_date', models.DateField(null=True)),
                ('admin_outcome', models.TextField(null=True)),
                ('admin_filepath', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.projects')),
                ('tesgnum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.tesg_admin')),
            ],
        ),
        migrations.CreateModel(
            name='temp_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=200, null=True)),
                ('dprsubdate', models.DateField(auto_now_add=True, null=True)),
                ('dprdenydate', models.DateField(auto_now_add=True, null=True)),
                ('amountasked', models.FloatField(null=True)),
                ('projectpath', models.TextField(null=True)),
                ('deny', models.BooleanField(default=False, max_length=1, null=True)),
                ('remark', models.TextField(null=True)),
                ('schedule', models.IntegerField(null=True)),
                ('removed', models.BooleanField(default=False, max_length=1, null=True)),
                ('submitted_boq', models.TextField(null=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.users')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.users'),
        ),
        migrations.CreateModel(
            name='Monitoring_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monipath', models.TextField(null=True)),
                ('monidate', models.DateField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.projects')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.users')),
            ],
        ),
        migrations.CreateModel(
            name='loadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche', models.IntegerField(default=0, null=True)),
                ('req_boq', models.TextField(null=True)),
                ('filepath', models.TextField(null=True)),
                ('subdate', models.DateField(auto_now_add=True, null=True)),
                ('compdate', models.DateField(null=True)),
                ('approved', models.CharField(default=2, max_length=1)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects')),
            ],
        ),
        migrations.CreateModel(
            name='init_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.TextField(default='Not available', null=True)),
                ('amount', models.IntegerField(null=True)),
                ('release_date', models.DateField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects')),
            ],
        ),
        migrations.CreateModel(
            name='boqdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boqtype', models.IntegerField(null=True)),
                ('itemno', models.IntegerField(null=True)),
                ('itemname', models.TextField(null=True)),
                ('itemdesc', models.TextField(null=True)),
                ('itemqty', models.IntegerField(null=True)),
                ('unitcost', models.FloatField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apprpath', models.TextField(null=True)),
                ('apprdate', models.DateField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.projects')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psdf_main.users')),
            ],
        ),
    ]
