# Generated by Django 3.2.5 on 2021-11-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0002_auto_20211101_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='init_payment',
            name='ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='init_payment',
            name='filepath',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='init_payment',
            name='recv_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='init_payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.users'),
        ),
    ]
