# Generated by Django 3.2.5 on 2021-11-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0003_auto_20211102_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadata',
            name='req_boq',
        ),
        migrations.RemoveField(
            model_name='loadata',
            name='tranche',
        ),
        migrations.AddField(
            model_name='loadata',
            name='amt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loadata',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loadata',
            name='remark',
            field=models.TextField(default='Not Available', null=True),
        ),
        migrations.AddField(
            model_name='loadata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.users'),
        ),
        migrations.AlterField(
            model_name='loadata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loadata',
            name='subdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='amt_approved',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='amt_asked',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='amt_released',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='quantumOfFunding',
            field=models.IntegerField(null=True),
        ),
    ]
