# Generated by Django 3.2.5 on 2021-11-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0004_auto_20211108_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.TextField(default='Not available', null=True)),
                ('amount', models.IntegerField(null=True)),
                ('release_date', models.DateField(auto_now_add=True, null=True)),
                ('recv_date', models.DateField(null=True)),
                ('filepath', models.TextField(null=True)),
                ('remark', models.TextField(default='Not Available', null=True)),
                ('ack', models.BooleanField(default=False)),
                ('loa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.loadata')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.projects')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psdf_main.users')),
            ],
        ),
    ]
