# Generated by Django 3.2.5 on 2021-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadata',
            name='ackdate',
            field=models.DateField(null=True),
        ),
    ]
