# Generated by Django 3.2.5 on 2021-11-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0006_loadata_ackdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadata',
            name='amt_released',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
