# Generated by Django 3.2.5 on 2021-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0007_loadata_amt_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ext1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='ext2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='ext3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='sanction_date',
            field=models.DateField(null=True),
        ),
    ]
