# Generated by Django 3.2.5 on 2021-11-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0008_auto_20211118_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal_admin',
            name='aprid',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='monitoring_admin',
            name='moniid',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='remark_date',
            field=models.DateField(null=True),
        ),
    ]
