# Generated by Django 3.2.5 on 2021-11-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0009_auto_20211123_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
