# Generated by Django 3.2.5 on 2021-11-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0012_auto_20211129_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='extF',
            field=models.TextField(null=True),
        ),
    ]
