# Generated by Django 3.2.5 on 2021-11-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0014_projects_amt_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='orischedule',
            field=models.IntegerField(null=True),
        ),
    ]
