# Generated by Django 3.2.5 on 2021-11-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0015_projects_orischedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqdata',
            name='itemqty',
            field=models.FloatField(null=True),
        ),
    ]
