# Generated by Django 3.2.5 on 2021-12-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0016_alter_boqdata_itemqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='aproutdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='monioutdate',
            field=models.DateField(null=True),
        ),
    ]
