# Generated by Django 3.2.5 on 2021-12-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psdf_main', '0018_auto_20211201_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqdata',
            name='itemqty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='boqdata',
            name='unitcost',
            field=models.FloatField(null=True),
        ),
    ]
